# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_b.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 751, 471))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.show_pushButton = QtWidgets.QPushButton(Form)
        self.show_pushButton.setGeometry(QtCore.QRect(90, 510, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Chiller")
        font.setPointSize(30)
        self.show_pushButton.setFont(font)
        self.show_pushButton.setObjectName("show_pushButton")
        self.next_pushButton_2 = QtWidgets.QPushButton(Form)
        self.next_pushButton_2.setGeometry(QtCore.QRect(510, 510, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Chiller")
        font.setPointSize(30)
        self.next_pushButton_2.setFont(font)
        self.next_pushButton_2.setObjectName("next_pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.show_pushButton.setText(_translate("Form", "Definition"))
        self.next_pushButton_2.setText(_translate("Form", "Next"))
