# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_b.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 371, 211))
        self.textEdit.setObjectName("textEdit")
        self.show_pushButton = QtWidgets.QPushButton(Form)
        self.show_pushButton.setGeometry(QtCore.QRect(50, 240, 91, 31))
        self.show_pushButton.setObjectName("show_pushButton")
        self.next_pushButton_2 = QtWidgets.QPushButton(Form)
        self.next_pushButton_2.setGeometry(QtCore.QRect(240, 240, 91, 31))
        self.next_pushButton_2.setObjectName("next_pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.show_pushButton.setText(_translate("Form", "Show meaning"))
        self.next_pushButton_2.setText(_translate("Form", "Next"))
